# games makefile

default: all

.DEFAULT:
	cd 23510004_SXTDH && $(MAKE) 
	cd 36610103_DDZ && $(MAKE) 
	cd 37460003_PHZ && $(MAKE) 
	cd 40000100_LHD && $(MAKE) 
	cd 50000001_BOOS && $(MAKE) 
	cd 12101105_ZJH && $(MAKE) 
	cd 30100008_NN && $(MAKE) 
	
install:
	cd 23510004_SXTDH && $(MAKE) $@
	cd 36610103_DDZ && $(MAKE) $@
	cd 37460003_PHZ && $(MAKE) $@
	cd 40000100_LHD && $(MAKE) $@
	cd 50000001_BOOS && $(MAKE) $@
	cd 12101105_ZJH && $(MAKE) $@
	cd 30100008_NN && $(MAKE) $@

clean:
	cd 23510004_SXTDH && $(MAKE) $@
	cd 36610103_DDZ && $(MAKE) $@
	cd 37460003_PHZ && $(MAKE) $@
	cd 40000100_LHD && $(MAKE) $@
	cd 50000001_BOOS && $(MAKE) $@
	cd 12101105_ZJH && $(MAKE) $@
	cd 30100008_NN && $(MAKE) $@

.PHONY: install
